// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxRy5SoItBPaMvGZY3886IPNFOmjbTpl4',
    appId: '1:495738642957:web:edc2dfb6f9a7b7de112b44',
    messagingSenderId: '495738642957',
    projectId: 'splitmate-aa',
    authDomain: 'splitmate-aa.firebaseapp.com',
    storageBucket: 'splitmate-aa.firebasestorage.app',
    measurementId: 'G-RNY4HQ5SFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuiyRcJ9r2GBt__5HLJITyGQRyx4EhIYk',
    appId: '1:495738642957:android:153bca55dce50e36112b44',
    messagingSenderId: '495738642957',
    projectId: 'splitmate-aa',
    storageBucket: 'splitmate-aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeacXBl1sm02Iip7WG09qabX31luLYlQs',
    appId: '1:495738642957:ios:08cde86667770eaf112b44',
    messagingSenderId: '495738642957',
    projectId: 'splitmate-aa',
    storageBucket: 'splitmate-aa.firebasestorage.app',
    iosBundleId: 'com.example.splitmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeacXBl1sm02Iip7WG09qabX31luLYlQs',
    appId: '1:495738642957:ios:08cde86667770eaf112b44',
    messagingSenderId: '495738642957',
    projectId: 'splitmate-aa',
    storageBucket: 'splitmate-aa.firebasestorage.app',
    iosBundleId: 'com.example.splitmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxRy5SoItBPaMvGZY3886IPNFOmjbTpl4',
    appId: '1:495738642957:web:a932eca56b4046b9112b44',
    messagingSenderId: '495738642957',
    projectId: 'splitmate-aa',
    authDomain: 'splitmate-aa.firebaseapp.com',
    storageBucket: 'splitmate-aa.firebasestorage.app',
    measurementId: 'G-XSLVKXZES2',
  );
}
